### ISSUE TITLE
Restructure Artworks and Artist data shape, to handle seed artworks data better

### ISSUE THREAD

**Issue by jonathannicolasdev** [jonathannicolasdev/nawaart-backend#3]
To handle the update, we have to do some certain steps:

1. Update the seed data of `artworks` to include the name slug of the `artist`.
2. Amend the seed controller to retrieve automatically the `artist`'s `ObjectID` and insert use that `ObjectID` to add an artwork.
3. Amend the add `artwork` controller to take the artist `ObjectId` from the request.
4. Amend the `artist` model to have `artworks` property, then put it with an array of `ObjectID` of `artworks`.

**Comment by mhaidarh** [comment]
```json
[
  {
  }
]
```

**Comment by jonathannicolasdev** [comment]
We can see artworks 
Step-1: Seed artists 
Step-2: Seed arworks
